#!/usr/bin/env bash
set -e
tests="$(cd "$(dirname "$0")" && pwd)"

rm -f "$tests/test.exe"
rm -f "$tests/shared.dll"

CXX="c++ -std=c++11 -Wall"
$CXX "$tests/shared.cpp" -o "$tests/shared.dll" -shared
$CXX "$tests/test.cpp"   -o "$tests/test.exe"

(cd "$tests" && "./test.exe")

rm -f "$tests/test.exe"
rm -f "$tests/shared.dll"